### ISSUE TITLE
OAuth2Strategy requires a clientID

### ISSUE THREAD

**Issue by lennyhiggins** [GainorB/node-express-starter#1]
When I try to npm start, I got this Issue
if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a client
ID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\Users\Carlos\Desktop\testing\oauth\node_modul
es\passport-oauth2\lib\strategy.js:82:34)
    at new Strategy (C:\Users\Carlos\Desktop\testing\oauth\node_modules\passport
-facebook\lib\strategy.js:54:18)
    at module.exports.passport (C:\Users\Carlos\Desktop\testing\oauth\config\pas
sport.js:95:5)
    at Object.<anonymous> (C:\Users\Carlos\Desktop\testing\oauth\server.js:81:29
)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE

**Comment by byabbas** [comment]
I'm getting the same problem, I'll let you know if I sort it out

**Comment by SAP1988** [comment]
@Abbas-Codes were you able to solve it?
